///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/cancion4.aks
/// Generation time: dom oct 27 21:10:52 CET 2019
///

/// Song 'song4' metadata macros
#define song4_address  0x0411
#define song4_size     305
#define song4_end      0x541

/// Song 'song4' array declaration
extern void song4[song4_size];
