///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/cancion3.aks
/// Generation time: dom oct 27 21:10:52 CET 2019
///

/// Song 'song3' metadata macros
#define song3_address  0x029e
#define song3_size     372
#define song3_end      0x411

/// Song 'song3' array declaration
extern void song3[song3_size];
