///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/cancion2.aks
/// Generation time: dom oct 27 21:10:52 CET 2019
///

/// Song 'song2' metadata macros
#define song2_address  0x01bd
#define song2_size     226
#define song2_end      0x29e

/// Song 'song2' array declaration
extern void song2[song2_size];
