///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/cancion1.aks
/// Generation time: dom oct 27 21:10:53 CET 2019
///

/// Song 'song' metadata macros
#define song_address  0x0040
#define song_size     382
#define song_end      0x1bd

/// Song 'song' array declaration
extern void song[song_size];
